import type { NextPage } from 'next';
import Head from 'next/head';
import GenericPageLayout from '../components/layouts/GenericPageLayouts';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <link rel="icon" href="/icon.svg" type="image/svg+xml" />
                <link rel="apple-touch-icon" href="icon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="manifest" href="site.webmanifest" />
                <meta name="theme-color" content="#fafafa" />
                <meta property="og:title" content=""/>
                <meta property="og:type" content=""/>
                <meta property="og:url" content=""/>
                <meta property="og:image" content=""/>
            </Head>
            <GenericPageLayout>
                <section>
                    <h1 style={ { fontFamily: 'cheddar gothic', fontSize: '3rem', fontWeight: 400 } }>L'iridescence industrielle de la méchanceté</h1>
                    <h1 style={ { fontFamily: 'metropolis', fontSize: '3rem', fontWeight: 400 } }>L'opalescente foisonnance de l'art nouveau Nancéen</h1>
                    <h1 style={ { fontFamily: 'ever looser', fontSize: '3rem', fontWeight: 400 } }>L'irruption du grondement sourd de la cité</h1>
                    <hr />
                    <h1>regular h1</h1>
                    <h2>regular h2</h2>
                    <h3>regular h3</h3>
                    <h4>regular h4</h4>
                    <h5>regular h5</h5>
                    <h6>regular h6</h6>
                    <p>You can use the mark tag to <mark>highlight</mark> text.</p>
                    <p><del>This line of text is meant to be treated as deleted text.</del></p>
                    <p><s>This line of text is meant to be treated as no longer accurate.</s></p>
                    <p><ins>This line of text is meant to be treated as an addition to the document.</ins></p>
                    <p><u>This line of text will render as underlined.</u></p>
                    <p><small>This line of text is meant to be treated as fine print.</small></p>
                    <p><strong>This line rendered as bold text.</strong></p>
                    <p><em>This line rendered as italicized text.</em></p>
                    <p><abbr title="attribute">attr</abbr></p>
                    <p><abbr title="HyperText Markup Language">HTML</abbr></p>
                    <blockquote>
                        <p>A well-known quote, contained in a blockquote element.</p>
                    </blockquote>
                    <figure>
                        <blockquote>
                            <p>A well-known quote, contained in a blockquote element.</p>
                        </blockquote>
                        <figcaption>
                            <cite title="Source Title">Someone famous in Source Title</cite>
                        </figcaption>
                    </figure>
                </section>
                <section>
                    <h2>Thématiques</h2>
                    <ol>
                        <li>
                            <a href="#">
                                <span>Histoires rêvées</span>
                                <time dateTime="2021-12-20">20 décembre 2021</time>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Chroniques de xiao xinzang</span>
                                <time dateTime="2021-12-19">19 décembre 2021</time>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Dieux illogiques</span>
                                <time dateTime="2021-12-18">18 décembre 2021</time>
                            </a>
                        </li>
                    </ol>
                </section>
                <section>
                    <h2>Articles</h2>
                    <ol>
                        <li>
                            <a href="#">
                                <span>Attaque de Kaiju: manuel de survie</span>
                                <time dateTime="2021-12-17">17 décembre 2021</time>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Attaque de zombies: manuel de survie</span>
                                <time dateTime="2021-12-16">16 décembre 2021</time>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span>Attaque de fanatiques religieux: manuel de survie</span>
                                <time dateTime="2021-12-15">15 décembre 2021</time>
                            </a>
                        </li>
                    </ol>
                </section>
            </GenericPageLayout>
        </>
    )
}

export default Home;
